// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	NodeMetadata
	FileMap
	FileMapEntry
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodeMetadata struct {
	NodeId           *uint64  `protobuf:"varint,1,req,name=node_id" json:"node_id,omitempty"`
	Size             *uint64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Atime            *uint64  `protobuf:"varint,4,opt,name=atime" json:"atime,omitempty"`
	Mtime            *uint64  `protobuf:"varint,5,opt,name=mtime" json:"mtime,omitempty"`
	Ctime            *uint64  `protobuf:"varint,6,opt,name=ctime" json:"ctime,omitempty"`
	Contents         *FileMap `protobuf:"bytes,7,opt,name=contents" json:"contents,omitempty"`
	Name             *string  `protobuf:"bytes,20,opt,name=name" json:"name,omitempty"`
	ParentNodeId     *uint64  `protobuf:"varint,21,opt,name=parent_node_id" json:"parent_node_id,omitempty"`
	Uid              *uint32  `protobuf:"varint,22,opt,name=uid" json:"uid,omitempty"`
	Gid              *uint32  `protobuf:"varint,23,opt,name=gid" json:"gid,omitempty"`
	Nlink            *uint32  `protobuf:"varint,24,opt,name=nlink" json:"nlink,omitempty"`
	Mode             *uint32  `protobuf:"varint,25,opt,name=mode" json:"mode,omitempty"`
	Symlink          []byte   `protobuf:"bytes,26,opt,name=symlink" json:"symlink,omitempty"`
	Valid            *bool    `protobuf:"varint,27,opt,name=valid" json:"valid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NodeMetadata) Reset()         { *m = NodeMetadata{} }
func (m *NodeMetadata) String() string { return proto.CompactTextString(m) }
func (*NodeMetadata) ProtoMessage()    {}

func (m *NodeMetadata) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *NodeMetadata) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *NodeMetadata) GetAtime() uint64 {
	if m != nil && m.Atime != nil {
		return *m.Atime
	}
	return 0
}

func (m *NodeMetadata) GetMtime() uint64 {
	if m != nil && m.Mtime != nil {
		return *m.Mtime
	}
	return 0
}

func (m *NodeMetadata) GetCtime() uint64 {
	if m != nil && m.Ctime != nil {
		return *m.Ctime
	}
	return 0
}

func (m *NodeMetadata) GetContents() *FileMap {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *NodeMetadata) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NodeMetadata) GetParentNodeId() uint64 {
	if m != nil && m.ParentNodeId != nil {
		return *m.ParentNodeId
	}
	return 0
}

func (m *NodeMetadata) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NodeMetadata) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *NodeMetadata) GetNlink() uint32 {
	if m != nil && m.Nlink != nil {
		return *m.Nlink
	}
	return 0
}

func (m *NodeMetadata) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *NodeMetadata) GetSymlink() []byte {
	if m != nil {
		return m.Symlink
	}
	return nil
}

func (m *NodeMetadata) GetValid() bool {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return false
}

type FileMap struct {
	Entry            []*FileMapEntry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FileMap) Reset()         { *m = FileMap{} }
func (m *FileMap) String() string { return proto.CompactTextString(m) }
func (*FileMap) ProtoMessage()    {}

func (m *FileMap) GetEntry() []*FileMapEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type FileMapEntry struct {
	Start            *uint64 `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	End              *uint64 `protobuf:"varint,2,req,name=end" json:"end,omitempty"`
	Base             *uint64 `protobuf:"varint,3,req,name=base" json:"base,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FileMapEntry) Reset()         { *m = FileMapEntry{} }
func (m *FileMapEntry) String() string { return proto.CompactTextString(m) }
func (*FileMapEntry) ProtoMessage()    {}

func (m *FileMapEntry) GetStart() uint64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *FileMapEntry) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func (m *FileMapEntry) GetBase() uint64 {
	if m != nil && m.Base != nil {
		return *m.Base
	}
	return 0
}
