// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	FileSegment
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FileSegment struct {
	Contents         []byte `protobuf:"bytes,1,opt,name=contents" json:"contents,omitempty"`
	FileId           *int64 `protobuf:"varint,2,opt,name=file_id" json:"file_id,omitempty"`
	Offset           *int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FileSegment) Reset()         { *m = FileSegment{} }
func (m *FileSegment) String() string { return proto.CompactTextString(m) }
func (*FileSegment) ProtoMessage()    {}

func (m *FileSegment) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *FileSegment) GetFileId() int64 {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return 0
}

func (m *FileSegment) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}
